name: Java CI with Gradle, Docker, Coveralls and SonarCloud in Linux

on:
   push:
   pull_request:
  
jobs:
   
  build:
    runs-on: ubuntu-latest
  
    steps:
     - uses: actions/checkout@v2
       with:
          # Shallow clones should be disabled for a better relevancy of SonarQube analysis
          fetch-depth: 0
     - name: Set up JDK 11
       uses: actions/setup-java@v1
       with:
          java-version: 11
     - name: Cache Maven packages
       uses: actions/cache@v2
       with:
          path: |
             ~/.m2
             ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-
#     - name: Download mysql image
#       run: docker pull mysql:8
#     - name: Build with Gradle
#       run: xvfb-run gradle build jar
#       working-directory: esame_attsw_Bellocci
#     - name: Jacoco
#       run: xvfb-run ./gradlew -PbuildProfile=jacoco jacocoTestReport
#       working-directory: examLibrary
#     - name: Pitest
#       run: xvfb-run gradle -PbuildProfile=pitest pitest
#       working-directory: esame_attsw_Bellocci
     - name: Coveralls
       run: gradle -PbuildProfile=coveralls jacocoTestReport coveralls
       working-directory: examLibrary
       env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
 